# Generated by Django 4.1 on 2022-08-12 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_remove_contact_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='added',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.BigIntegerField(blank=True, max_length=12, null=True),
        ),
    ]
