# Generated by Django 4.1 on 2022-08-12 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0002_remove_person_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='phone',
            field=models.BigIntegerField(blank=True, max_length=12, null=True),
        ),
    ]
